name: Cache Renew

on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: "0 0 * * 1"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Cache node modules
        id: cache
        uses: actions/cache/restore@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-24.x-node-modules-hash-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-24.x-node-modules-hash-${{ hashFiles('yarn.lock') }}
