name: Cypress + Chromatic

on: pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Workday/canvas-kit-actions/install@v1
        with:
          node_version: 24.x

  cypress-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Workday/canvas-kit-actions/install@v1
        with:
          node_version: 24.x

      - name: Run Cypress e2e tests
        run: yarn cy:e2e
        env:
          CYPRESS_CACHE_FOLDER: .cache/cypress
          ELECTRON_EXTRA_LAUNCH_ARGS: --remote-debugging-port=9222
          
      - uses: chromaui/action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
          cypress: true
          exitOnceUploaded: false
          exitZeroOnChanges: true
