name: Pull Request

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Workday/canvas-kit-actions/install@v1
        with:
          node_version: 24.x

      - name: Build project graph
        shell: bash
        run: npx nx show projects
        env:
          NX_DAEMON: 'false'

      - name: Build project
        shell: bash
        run: yarn build

      - name: Lint
        shell: bash
        run: yarn lint

      - name: Type Check
        shell: bash
        run: yarn typecheck
